### PR TITLE
uploaded some components

### PR DESCRIPTION
**Pull request by radistoubalidis**
- Added these components : SearchMovie.vue , SearchAdmin.vue , Title.vue , Avatar.vue , RegisterButton.vue , LoginButton.vue , AppBarAdmin.vue , CarouselList.vue , 
- Added /pages folder with index.vue
- Added layouts/error.vue and modified layouts/default.vue

- Issue : vuetify element don't render

### CODE REVIEW

**Comment by dPliakos** [comment]
Please rename the `/src/client-app/components/Moviecard.vue` file to use camel case  `MovieCard.vue` and add the `'@nuxtjs/vuetify'` entry at the nuxt.config.json

```js
{

  buildModules: [
      '@nuxtjs/vuetify',
  ],
}
```

**Comment by radistoubalidis** [comment]
Uploaded rest of the components and pages
see images below there's a build error
changes
error

**Comment by Mr-Watch** [comment]
Did you happen to modify any of the css/sass properties ?
That overflow : hidden looks to me like a css property that is malformed.
This could be the reason why it is not parsing it correctly.

**Comment by radistoubalidis** [comment]
> 
> 
> Did you happen to modify any of the css/sass properties ?
> That overflow : hidden looks to me like a css property that is malformed.
> This could be the reason why it is not parsing it correctly.

Οχι δεν αλλαξα κατι αλλα ξεκινησε να γινεται οταν προσθεσα το vuetify

**Comment by radistoubalidis** [comment]
Just fixed build error with this command 'npm install sass@1.32.8'

**Comment by radistoubalidis** [comment]
update 20-4 addded these components
chages 20-4

**Comment by radistoubalidis** [comment]
Fixed Build Error !

**Pull request merged**
